# Generated by Django 5.0.6 on 2024-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_email_verified_account_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="nickname",
            field=models.CharField(default="unkown", max_length=20),
        ),
    ]
