# Generated by Django 5.0.6 on 2024-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_google",
            field=models.BooleanField(default=False),
        ),
    ]
