# Generated by Django 4.2.6 on 2024-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_is_google"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="nickname",
            field=models.CharField(default="unkown", max_length=100),
        ),
    ]
