# Generated by Django 5.0.6 on 2024-05-27 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_details", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_weight", models.FloatField(blank=True, null=True)),
                ("goal_body_fat", models.FloatField(blank=True, null=True)),
                ("goal_consume_cal", models.FloatField(blank=True, null=True)),
                ("goal_intake_cal", models.FloatField(blank=True, null=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaticDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tall", models.FloatField(blank=True, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("male", "male"), ("female", "female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("bmr", models.FloatField(blank=True, null=True)),
                (
                    "active_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "low"),
                            ("middle", "middle"),
                            ("high", "high"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
