# Generated by Django 5.0.6 on 2024-05-27 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_details", "0002_goaldetail_staticdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicdetail",
            name="body_fat",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="staticdetail",
            name="active_level",
            field=models.CharField(
                choices=[("low", "low"), ("middle", "middle"), ("high", "high")],
                default="low",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="staticdetail",
            name="bmr",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="staticdetail",
            name="tall",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
