# Generated by Django 5.0.6 on 2024-06-14 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_details", "0006_remove_goaldetail_current_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticdetail",
            name="other_cal",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
