# Generated by Django 5.0.6 on 2024-05-30 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0005_rename_meal_date_meal_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatSecretFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("brand_name", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(max_length=2000)),
                ("description", models.TextField()),
                ("calories_per_unit", models.FloatField()),
                ("fat_per_unit", models.FloatField()),
                ("carbs_per_unit", models.FloatField()),
                ("protein_per_unit", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="food",
            name="ex_api_id",
        ),
        migrations.AlterField(
            model_name="meal",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meals.food",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="fat_secret_food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meals.fatsecretfood",
            ),
        ),
    ]
