# Generated by Django 5.0.6 on 2024-05-31 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0006_fatsecretfood_remove_food_ex_api_id_alter_meal_food_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatsecretfood",
            name="calories_per_unit",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="fatsecretfood",
            name="carbs_per_unit",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="fatsecretfood",
            name="fat_per_unit",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="fatsecretfood",
            name="protein_per_unit",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
