# Generated by Django 5.0.6 on 2024-05-31 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0007_alter_fatsecretfood_calories_per_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="intake_carbs",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="intake_fat",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="intake_protein",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="intake_cal",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
