# Generated by Django 5.0.6 on 2024-06-14 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0010_mealset_mealpre"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealpre",
            name="intake_cal",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
