# Generated by Django 5.0.6 on 2024-06-19 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0011_mealpre_intake_cal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fatsecretfood",
            old_name="calories_per_unit",
            new_name="cal",
        ),
        migrations.RenameField(
            model_name="fatsecretfood",
            old_name="carbs_per_unit",
            new_name="carb",
        ),
        migrations.RenameField(
            model_name="fatsecretfood",
            old_name="fat_per_unit",
            new_name="fat",
        ),
        migrations.RenameField(
            model_name="fatsecretfood",
            old_name="protein_per_unit",
            new_name="protein",
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="calcium",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="cholesterol",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="dietary_fiber",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="iron",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="magnesium",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="monounsaturated_fat",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="niacin",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="polyunsaturated_fat",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="potassium",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="salt",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="saturated_fat",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="sodium",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="sugars",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="vitamin_a",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="vitamin_b1",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="vitamin_b12",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="vitamin_b2",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="vitamin_b6",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="vitamin_c",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="vitamin_d",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="vitamin_e",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="fatsecretfood",
            name="zinc",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="monounsaturated_fat",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="polyunsaturated_fat",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="fatsecretfood",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
