# Generated by Django 5.0.6 on 2024-06-19 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0013_fatsecretfood_food_sub_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fatsecretfood",
            name="food_sub_category",
        ),
    ]
