# Generated by Django 5.0.6 on 2024-06-19 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0014_remove_fatsecretfood_food_sub_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="custom",
        ),
        migrations.RemoveField(
            model_name="food",
            name="food_type",
        ),
        migrations.RemoveField(
            model_name="food",
            name="often",
        ),
        migrations.AlterField(
            model_name="food",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
