# Generated by Django 5.0.6 on 2024-06-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monsters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="monster_type",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("Premium", "Premium"), ("Cat", "Cat")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="monsterselected",
            name="selected_monster",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("Premium", "Premium"), ("Cat", "Cat")],
                max_length=50,
            ),
        ),
    ]
