# Generated by Django 4.2.6 on 2024-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monsters", "0002_alter_monster_monster_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="monster_type",
            field=models.CharField(
                choices=[
                    ("Normal", "Normal"),
                    ("Premium", "Premium"),
                    ("Cat", "Cat"),
                    ("Flame", "Flame"),
                    ("Ghost", "Ghost"),
                    ("Dog", "Dog"),
                    ("Dinosaur", "Dinosaur"),
                    ("Metal", "Metal"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="monsterselected",
            name="selected_monster",
            field=models.CharField(
                choices=[
                    ("Normal", "Normal"),
                    ("Premium", "Premium"),
                    ("Cat", "Cat"),
                    ("Flame", "Flame"),
                    ("Ghost", "Ghost"),
                    ("Dog", "Dog"),
                    ("Dinosaur", "Dinosaur"),
                    ("Metal", "Metal"),
                ],
                max_length=50,
            ),
        ),
    ]
