# Generated by Django 5.0.6 on 2024-06-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("license", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="is_subscription_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="license",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
