# Generated by Django 5.0.6 on 2024-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="type",
            field=models.CharField(
                choices=[
                    ("Living", "Living"),
                    ("Aerobic", "Aerobic"),
                    ("Walk", "Walk"),
                    ("Run", "Run"),
                    ("Muscle", "Muscle"),
                    ("Sports Club", "Sports Club"),
                    ("Martial Arts", "Martial Arts"),
                    ("Marine Winter", "Marine Winter"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
