# Generated by Django 5.0.6 on 2024-05-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_alter_workout_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="custom",
            field=models.BooleanField(default=False),
        ),
    ]
