# Generated by Django 5.0.6 on 2024-05-26 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0003_workout_custom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="consumed_cal",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
