# Generated by Django 5.0.6 on 2024-05-26 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0004_alter_exercise_consumed_cal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="consumed_cal",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
