# Generated by Django 5.0.6 on 2024-05-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0008_alter_workout_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="ja_name",
            field=models.CharField(
                blank=True,
                default=models.CharField(max_length=50),
                max_length=50,
                null=True,
            ),
        ),
    ]
