# Generated by Django 5.0.6 on 2024-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0009_workout_ja_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="ja_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
