# Generated by Django 5.0.6 on 2024-05-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0010_alter_workout_ja_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="ja_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="workout",
            name="type",
            field=models.CharField(
                choices=[
                    ("Daily Living Activities", "Daily Living Activities"),
                    ("Cardio", "Cardio"),
                    ("Walking/Running", "Walking/Running"),
                    ("Strength Training", "Strength Training"),
                    ("Fitness", "Fitness"),
                    ("Ball Sports", "Ball Sports"),
                    ("Martial Arts", "Martial Arts"),
                    ("Water and Winter Sports", "Water and Winter Sports"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
