# Generated by Django 5.0.6 on 2024-05-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0011_alter_workout_ja_name_alter_workout_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="type",
            field=models.CharField(
                choices=[
                    ("Daily Living Activities", "Daily Living Activities"),
                    ("Cardio", "Cardio"),
                    ("Walking・Running", "Walking・Running"),
                    ("Strength Training", "Strength Training"),
                    ("Fitness", "Fitness"),
                    ("Ball Sports", "Ball Sports"),
                    ("Martial Arts", "Martial Arts"),
                    ("Water and Winter Sports", "Water and Winter Sports"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
